# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello <- function() {
    .Call(`_SA230104157_rcpp_hello`)
}

#' @title fibo
#' @description fibo sampler using Rcpp
#' @param n the number of samples
#' @return fibo sampler using Rcpp \code{n}
#' @examples
#' \dontrun{
#' a <- fibo(5)
#' }
#' @export
fibo <- function(n) {
    .Call(`_SA230104157_fibo`, n)
}

#' @title rcppc is isprime
#' @description isprime sampler using Rcpp
#' @param x the number of samples
#' @return is or not rpime using Rcpp \code{n}
#' @examples
#' \dontrun{
#' b <- rcppc(5)
#' }
#' @export
rcppc <- function(x) {
    .Call(`_SA230104157_rcppc`, x)
}

